[package]
name = "eol-deployer"
version = "0.1.0"
edition = "2024"
description = "A tool for deploying new versions of traefik configs"
authors = ["Ari Lerner <me@ari.io>"]
license = "MIT"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }

[package.metadata.release]
# This section is used by cargo-release for release automation.
