name: Deploy Oranda to GitHub Pages

on:
  push:
    tags:
      - "**[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-oranda:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Oranda
        run: cargo install oranda

      - name: Build Oranda site
        run: oranda build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
